server:
  port: 8080
spring:
  datasource:
    name: springboot
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter: stat
      driver-class-name: com.mysql.jdbc.driver
      url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&?zeroDateTimeBehavior=convertToNull
      username: root
      password: qwe123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    mode: LEGACYHTML5
    cache: false
  servlet:
    multipart:
      max-file-size: 10mb
      max-request-size: 100mb
  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: true
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-idle: 8
        min-idle: 8
        max-wait: -1
        max-active: 8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.tycoding.entity
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true
logging:
  level:
    cn.tycoding.mapper:DEBUG
